"use client";
import { FormEvent, useEffect, useState } from "react";
type Tenant={id:string;name:string;status:string;created_at:string};
export default function Home(){
  const [tenants,setTenants]=useState<Tenant[]|null>(null),[error,setError]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState("");
  const load=()=>fetch("/api/platform/tenants").then(async r=>{if(r.status===401)throw new Error("AUTH");if(!r.ok)throw new Error("Kiracılar yüklenemedi");return r.json()}).then(setTenants).catch(e=>setError(e.message));
  useEffect(()=>{void load()},[]);
  async function login(e:FormEvent){e.preventDefault();const r=await fetch("/api/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,password})});if(r.ok){setError("");void load()}else setError("Giriş başarısız")}
  if(tenants===null&&error==="AUTH")return <main className="login"><p className="eyebrow">Kontrol düzlemi</p><h1>Sükûnetle yönet.</h1><p className="statement">İyi bir sistem, görünmez olduğunda en iyi hâlindedir.</p><form onSubmit={login}><label>E-posta<input type="email" required autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Parola<input type="password" required autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary">İçeri gir</button></form>{error!=="AUTH"&&<p role="alert">{error}</p>}</main>;
  return <main className="wrap"><div className="top"><div><p className="eyebrow">Platform / Kiracılar</p><h1>Bütünü gör.</h1><p className="statement">Her işletme kendi dünyasıdır. Platform, bu dünyaların sessizce işlemesini sağlar.</p></div><button onClick={()=>fetch("/api/logout",{method:"POST"}).then(()=>location.reload())}>Oturumu kapat</button></div>{error&&<p role="alert">{error}</p>}{tenants===null?<p>Görünüm hazırlanıyor…</p>:<div className="card"><div className="table-wrap" tabIndex={0} role="region" aria-label="Kiracı listesi"><table><thead><tr><th>İşletme</th><th>Yaşam durumu</th><th>Başlangıç</th></tr></thead><tbody>{tenants.map(t=><tr key={t.id}><td><a href={`/tenants/${t.id}`}>{t.name}</a></td><td><span className="badge">{t.status==="active"?"Etkin":"Askıda"}</span></td><td>{new Date(t.created_at).toLocaleDateString("tr-TR")}</td></tr>)}</tbody></table></div>{!tenants.length&&<p>Henüz bir işletme yok. Boşluk da bir başlangıçtır.</p>}</div>}</main>;
}
